name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2] # Usa 2 instâncias paralelas

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use a versão do Node.js compatível com seu projeto
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          record: true # Grava os testes no Cypress Cloud
          parallel: true # Executa os testes em paralelo
          browser: chrome # Define o navegador padrão (opcional)
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} # Chave de gravação do Cypress Cloud
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token do GitHub para integração
          MESA_LOADER_DRIVER_OVERRIDE: "swrast" # Adiciona a variável de ambiente para desativar o uso do ZINK

      - name: Verify Cypress test results
        run: |
          if [ ! -d "cypress/screenshots" ] || [ ! -d "cypress/videos" ]; then
            echo "No Cypress test results found."
            exit 1

      - name: Upload Cypress screenshots and videos (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-and-videos-${{ matrix.containers }}-${{ github.run_id }}
          path: |
            cypress/screenshots
            cypress/videos